USE educafe;
INSERT INTO categorias VALUES (1,"cafés",null,null);
INSERT INTO categorias VALUES (2,"bebidas",null,null);
INSERT INTO categorias VALUES (3,"bocadillos",null,null);
INSERT INTO categorias VALUES (4,"dulces",null,null);
INSERT INTO categorias VALUES (5,"salados",null,null);
INSERT INTO categorias VALUES (6,"snacks",null,null);

USE educafe;
INSERT INTO productos VALUES (1,1,"café solo","Nuestro expresso más sabroso, con todo nuestro aroma de siempre. ¡Un clásico!",0.7,null,null);
INSERT INTO productos VALUES (2,1,"café cortado", "¡El típico! Perfecto para los que necesitan el café con un toque de leche",0.8,null,null);
INSERT INTO productos VALUES (3,1, "café bombón",  "El más dulce nuestros cafés. ¡Endúlzate el día!",0.8,null, null);
INSERT INTO productos VALUES (4,1,"vaso de leche", "Porque no todo el mundo quiere café, tu aporte lácteo del día",1.0,null,null);
INSERT INTO productos VALUES (5,1,"colacao","La alegría necesaria para el vaso de leche, ¡el Cola-Cao!",1.1,null,null);
INSERT INTO productos VALUES (6,1,"capuccino", "Para los más exigentes y que necesitan algo más que café",1.2, null,null);
INSERT INTO productos VALUES (7,1,"café americano","Las tazas grandes no siempre tienen que tener la combinación de café y leche, ¡puede ser café y agua!",0.8,null,null);
INSERT INTO productos VALUES (8,1,"café del tiempos","¡El rey contra el calor! Nuestro expresso con hielo y limón", 1.2, null, null);
INSERT INTO productos VALUES (9,2,"Coca-cola","La lata de Coca-Cola de toda la vida, ¡refrescante!",1.2,null,null);
INSERT INTO productos VALUES (10,2,"Coca-cola zero","El mejor sabor de Coca-Cola con cero azúcar",1.2, null, null);
INSERT INTO productos VALUES (11,2,"Fanta naranja/limón","Tú eliges, ¿eres más de naranja o de limón?",1.2,null,null);
INSERT INTO productos VALUES (12,2,"Aquarius naranja/limón","LA bebida de los deportistas",1.3,null,null);
INSERT INTO productos VALUES (13,2,"Monster verde","La energía extra que necesitas cuando no puedes más",2.0,null,null);
INSERT INTO productos VALUES (14,2,"Red Bull","Todos necesitamos que nos den alas para rendir mejor",2.2,null,null);
INSERT INTO productos VALUES (15,2,"Zumos", "Los mejores zumos naturales de frutas de proximidad",1.2,null,null);
INSERT INTO productos VALUES (16,2,"Batidos","Agítalos bien antes de tomarlos, ¡te endulzarán!",1.2,null,null);
INSERT INTO productos VALUES (17,2,"Bifrutas","El brick más sabroso y vitaminado",1.2,null,null);
INSERT INTO productos VALUES (18,2,"Agua pequeña","Para quien quiere matar su sed rápidamente",0.8,null,null);
INSERT INTO productos VALUES (19,2,"Agua con gas","Hay quien necesita el agua con algo más",0.8,null,null);
INSERT INTO productos VALUES (20,2,"Agua grande 1.5 L.","El depósito de gasolina para tu día a día",1.2,null,null);
INSERT INTO productos VALUES (21,3,"Bocadillo pequeño","Apodado el “quita-hambres”, tremendamente sabroso",2.0,null,null);
INSERT INTO productos VALUES (22,3,"Bocadillo completo","La estrella del menú, pídelo con los ingredientes que más te gusten",2.0,null,null);
INSERT INTO productos VALUES (23,3,"Pulga (montadito)","El bocadillo más rápido de todo el oeste, forastero",1.70,null,null);
INSERT INTO productos VALUES (24,3,"Paninis","Aroma italiano en nuestra cafetería",1.2,null,null);
INSERT INTO productos VALUES (25,4,"Caracolas","Enróllate con nuestras delicias",0.5,null,null );
INSERT INTO productos VALUES (26,4,"MiniEnsaimadas","Porque las cosas pequeñas también son sabrosas y dulces",0.5,null,null);
INSERT INTO productos VALUES (27,4,"Caracola Grande","Siempre alguien tiene más apetito, con ella te saciarás",1.2,null,null);
INSERT INTO productos VALUES (28,4,"Triángulo de chocolate","El dulce más apreciado por los estudiantes de trigonometría",1.5,null,null);
INSERT INTO productos VALUES (29,5,"Empanadilla de pisto","El topicazo de la cafetería, no podía faltar",1.5,null,null);
INSERT INTO productos VALUES (30,5,"Empanadilla de espinacas","Las favoritas de Popeye",1.5,null,null);
INSERT INTO productos VALUES (31,5,"Napolitanas jamón/queso","La mejor combinación: jamón y queso. ¡Inigualable!",1.5,null,null);
INSERT INTO productos VALUES (32,5,"Rosquilletas","Lo más crujiente que tenemos, todos las quieren",1.5,null,null);
INSERT INTO productos VALUES (33,6,"Mikado","Para entretenerse y disfrutar",1.2,null,null);
INSERT INTO productos VALUES (34,6,"Oreo","El sabor de siempre a un precio irresistible",1.2,null,null);
INSERT INTO productos VALUES (35,6,"Kinder blanco/negro","Elige tu sabor favorito, blanco o negro",1.2,null,null);
INSERT INTO productos VALUES (36,6,"Krits","Algo salado para contrarrestar tanto dulce",1.2,null,null);
INSERT INTO productos VALUES (37,6,"Filipinos","Están tan buenos que te los comerás sin darte cuenta",1.0,null,null);
INSERT INTO productos VALUES (38,6,"Halls","Los caramelos favoritos de Chiquito de la Calzada",1.0,null,null);
INSERT INTO productos VALUES (39,6,"Chuches grande","¡El bolsón! Y no de la comarca de la Tierra Media",1.0,null,null);
INSERT INTO productos VALUES (40,6,"Chuches pequeña","Se adapta a cualquier bolsillo. Siempre disponible para una emergencia dulce",0.5,null,null);

-- USE educafe;
-- INSERT INTO carritos VALUES ("1674200412599", "20-01-2023", 1, 2, null,null,null);
-- INSERT INTO carritos VALUES ("1674200412599", "20-01-2023", 0, 2, null,null,null);
-- INSERT INTO carritos VALUES ("1674200412599", "20-01-2023", 0, 2, null,null,null);

USE educafe;
INSERT INTO usuarios VALUES (1,"prueba@gmail.com",null,"1234",null,null,null);
INSERT INTO usuarios VALUES (2,"joseluis@gmail.com",null,"1234",null,null,null);
INSERT INTO usuarios VALUES (3,"pau@gmail.com",null,"1234",null,null,null);
INSERT INTO usuarios VALUES (4,"elena@gmail.com",null,"1234",null,null,null);
INSERT INTO usuarios VALUES (5,"yasmina@gmail.com",null,"1234",null,null,null);

USE educafe;
INSERT INTO pagos VALUES (1,"PAU FANDOS GORRIS","1111-1111-1111-1111",234,"11/25","1674200412599",1,null,null);
INSERT INTO pagos VALUES (2,"PAU FANDOS GORRIS","1111-1111-1111-1111",234,"11/25","1674200512390",1,null,null);
